/**
 * extract-specs.js
 * 从站内产品数据（products.ts / products-materials.ts）的标题+描述，以及 shopify-map.ts 的
 * shopifyHandle 中提取：尺寸（归一化为 cm）和材质（关键词词典），生成 src/data/product-specs.ts
 *
 * 提取不到的字段留空（前台对应行不显示）。手工修正写在 src/data/specs-overrides.ts（前台优先）。
 * 用法：node scripts/extract-specs.js
 */

const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'src', 'data');

// ---------- 读取产品文本（asin/title/handle/description 字段顺序固定，JSON 风格字符串） ----------
const PRODUCT_RE = /"asin":\s*("(?:[^"\\]|\\.)*"),\s*"title":\s*("(?:[^"\\]|\\.)*"),\s*"handle":\s*("(?:[^"\\]|\\.)*"),\s*"description":\s*("(?:[^"\\]|\\.)*")/g;

function loadProducts(file) {
  const src = fs.readFileSync(path.join(DATA_DIR, file), 'utf-8');
  const out = [];
  let m;
  while ((m = PRODUCT_RE.exec(src))) {
    out.push({
      asin: JSON.parse(m[1]),
      title: JSON.parse(m[2]),
      handle: JSON.parse(m[3]),
      description: JSON.parse(m[4]),
    });
  }
  return out;
}

// ---------- 尺寸提取 ----------
const DIM_RE = /(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)(?:\s*[x×]\s*(\d+(?:\.\d+)?))?\s*(cm|mm|inches|inch|in|")(?![a-z])/gi;
// 引号写法：44" x 21" x 4.5"
const DIM_QUOTE_RE = /(\d+(?:\.\d+)?)"\s*[x×]\s*(\d+(?:\.\d+)?)"(?:\s*[x×]\s*(\d+(?:\.\d+)?)")?/;

function toCm(value, unit) {
  const v = parseFloat(value);
  const u = unit.toLowerCase();
  if (u === 'cm') return v;
  if (u === 'mm') return v / 10;
  return v * 2.54; // in / inches / inch / "
}

function extractDims(text) {
  if (!text) return null;
  DIM_RE.lastIndex = 0;
  const m = DIM_RE.exec(text);
  if (m) {
    const dims = [toCm(m[1], m[4]), toCm(m[2], m[4])];
    if (m[3]) dims.push(toCm(m[3], m[4]));
    return dims.map(d => Math.round(d * 10) / 10);
  }
  const q = DIM_QUOTE_RE.exec(text);
  if (q) {
    const dims = [toCm(q[1], '"'), toCm(q[2], '"')];
    if (q[3]) dims.push(toCm(q[3], '"'));
    return dims.map(d => Math.round(d * 10) / 10);
  }
  return null;
}

// handle 预处理：修复小数（4-5-inch → 4.5-inch），再把连字符变空格
function handleToText(handle) {
  return handle
    .replace(/(\d)-(\d)(?=-(?:inch|in|cm|mm)\b)/g, '$1.$2')
    .replace(/-/g, ' ');
}

// ---------- 材质提取（靠前的更具体，先匹配） ----------
const MATERIAL_KEYWORDS = [
  ['memory foam', 'Memory Foam'],
  ['pp cotton', 'PP Cotton'],
  ['hollowfibre', 'Hollowfibre'],
  ['hollowfiber', 'Hollowfibre'],
  ['down alternative', 'Down Alternative'],
  ['coral fleece', 'Coral Fleece'],
  ['crystal velvet', 'Crystal Velvet'],
  ['microfiber', 'Microfiber'],
  ['polyester', 'Polyester'],
  ['chenille', 'Chenille'],
  ['flannel', 'Flannel'],
  ['sherpa', 'Sherpa'],
  ['velvet', 'Velvet'],
  ['cotton', 'Cotton'],
  ['linen', 'Linen'],
  ['rattan', 'Rattan'],
  ['wicker', 'Wicker'],
  ['jute', 'Jute'],
  ['sisal', 'Sisal'],
  ['bamboo', 'Bamboo'],
  ['oxford', 'Oxford Fabric'],
  ['canvas', 'Canvas'],
  ['acrylic', 'Acrylic'],
  ['nylon', 'Nylon'],
  ['leather', 'Leather'],
  ['rubber', 'Rubber'],
  ['coir', 'Coir'],
  ['wool', 'Wool'],
];

function extractMaterial(text) {
  const lower = ` ${text.toLowerCase()} `;
  const found = [];
  for (const [kw, display] of MATERIAL_KEYWORDS) {
    const re = new RegExp(`\\b${kw.replace(/ /g, '\\s+')}\\b`);
    if (re.test(lower) && !found.includes(display)) found.push(display);
  }
  return found.length ? found.join(', ') : null;
}

// ---------- 主流程 ----------
function main() {
  const products = [...loadProducts('products.ts'), ...loadProducts('products-materials.ts')];
  console.log(`Products loaded: ${products.length}`);

  const specs = {};
  let withDims = 0, withMaterial = 0;
  const noDims = [];

  for (const p of products) {
    const key = p.asin.toLowerCase();
    // 尺寸来源优先级：标题 > 描述 > 站内 handle。
    // 注意：不使用 shopifyHandle —— Shopify 存在错配记录（如 b098f1bkjq 实际是椅垫产品），
    // 其 handle 里的尺寸会张冠李戴
    const dims =
      extractDims(p.title) ||
      extractDims(p.description) ||
      extractDims(handleToText(p.handle));
    const material = extractMaterial(`${p.title} ${p.description}`);

    const entry = {};
    if (dims) entry.dimensionsCm = dims;
    if (material) entry.material = material;
    if (dims || material) specs[key] = entry;
    if (dims) withDims++; else noDims.push(`${key}  ${p.title.slice(0, 70)}`);
    if (material) withMaterial++;
  }

  const entries = Object.entries(specs)
    .map(([k, v]) => {
      const parts = [];
      if (v.dimensionsCm) parts.push(`dimensionsCm: [${v.dimensionsCm.join(', ')}]`);
      if (v.material) parts.push(`material: "${v.material}"`);
      return `  "${k}": { ${parts.join(', ')} },`;
    })
    .join('\n');

  const ts = `// Auto-generated by scripts/extract-specs.js
// DO NOT EDIT MANUALLY - Run 'node scripts/extract-specs.js' to update
// Generated at: ${new Date().toISOString()}
// 尺寸/材质提取覆盖表（key = 小写 ASIN）。手工修正在 specs-overrides.ts（前台优先）

export interface ProductSpecs {
  /** 尺寸（cm，2-3 维），来源：标题/描述/handle 提取 */
  dimensionsCm?: number[];
  /** 材质（展示字符串） */
  material?: string;
}

export const PRODUCT_SPECS: Record<string, ProductSpecs> = {
${entries}
};
`;
  fs.writeFileSync(path.join(DATA_DIR, 'product-specs.ts'), ts, 'utf-8');

  console.log(`\nCoverage: dimensions ${withDims}/${products.length}, material ${withMaterial}/${products.length}`);
  console.log(`Written to src/data/product-specs.ts (${Object.keys(specs).length} entries)`);
  if (noDims.length) {
    console.log(`\nNo dimensions found (${noDims.length}), first 20:`);
    noDims.slice(0, 20).forEach(s => console.log(`  ${s}`));
  }
}

main();
