// Auto-generated by scripts/build-weights.js
// DO NOT EDIT MANUALLY - 人工赋权改 src/data/weights-overrides.ts 后重跑本脚本
// Generated at: 2026-09-19T14:59:44.563Z

export interface ProductWeight {
  /** 一级类目（同分破平用类目平均分） */
  type: string;
  /** 总分 = 表现分 + 人工 boost（±30 封顶） */
  score: number;
  /** 自动表现分（销量 60 / 新鲜度 15 / 评价 15 / 内容 10） */
  perf: number;
  /** 人工加减分 */
  boost: number;
  /** 硬置顶位次（1 起，凌驾于排序） */
  pin?: number;
  /** 沉底：排在在售组末尾 */
  buried?: boolean;
  /** 排除：权重排序场景不展示 */
  excluded?: boolean;
}

export const PRODUCT_WEIGHTS: Record<string, ProductWeight> = {
  "b098f1bkjq": {"type":"Others","score":8,"perf":8,"boost":0},
  "b0bbzsgdbq": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0bbzw4lzr": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0bcjqyyl1": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0bxckknn8": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0cqc6h9mz": {"type":"Pillows","score":49.9,"perf":19.9,"boost":30},
  "b0bzcln57s": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0bzcmdzns": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c2z9jrdm": {"type":"Others","score":8,"perf":8,"boost":0},
  "b0c2z9pffk": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c2zcxvx7": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c33lfhn1": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c33lpy5g": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c33lxrvk": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c33lz5pw": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c33m24l3": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c39zmk7h": {"type":"Cushions","score":8,"perf":8,"boost":0},
  "b0c39zsd3q": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c3b12dl7": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c3b13n8z": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c3b16l6r": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c3b265xj": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4b9t6jv": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4bbvs53": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4bc7q4s": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4bcd4dy": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4bd7q5x": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c4bdllfk": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c69qnsb3": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c69rjvvt": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c69rr6gf": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c69rryxm": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c6h5xzmz": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0c8j237v3": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0c8j292wf": {"type":"Others","score":17.9,"perf":17.9,"boost":0},
  "b0cbt7b1ty": {"type":"Cushions","score":44.9,"perf":19.9,"boost":25},
  "b0cbt7r7nn": {"type":"Cushions","score":44.9,"perf":19.9,"boost":25},
  "b0cbt7rfk2": {"type":"Cushions","score":44.9,"perf":19.9,"boost":25},
  "b0cc5rgrps": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cc5tlwfs": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cc5vnqy3": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cc5wn6jj": {"type":"Cushions","score":44.9,"perf":19.9,"boost":25},
  "b0cc5y77dc": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cj8tjl56": {"type":"Cushions","score":10,"perf":10,"boost":0},
  "b0cjhslcz5": {"type":"Cushions","score":8.5,"perf":8.5,"boost":0},
  "b0cjhx7xkl": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cqbzm49v": {"type":"Pillows","score":19.9,"perf":19.9,"boost":0},
  "b0cqc5qjfj": {"type":"Pillows","score":19.9,"perf":19.9,"boost":0},
  "b0by8ly757": {"type":"Others","score":6,"perf":6,"boost":0},
  "b0cw182mcy": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cw193n7m": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cw19gmpq": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cw1h96y5": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0cxdzf2wq": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0d5dnwx8j": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0d9lh1y55": {"type":"Others","score":6,"perf":6,"boost":0},
  "b0f1xfwzvy": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0f1xmtync": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0f1xs27xs": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0f1xs7vky": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0f1y4j48t": {"type":"Cushions","score":10,"perf":10,"boost":0},
  "b0f1y91hpr": {"type":"Cushions","score":8,"perf":8,"boost":0},
  "b0f62xrb55": {"type":"Pillows","score":10,"perf":10,"boost":0},
  "b0fnqrrv78": {"type":"Cushions","score":19.9,"perf":19.9,"boost":0},
  "b0g6m3f7cy": {"type":"Pillows","score":16.9,"perf":16.9,"boost":0},
  "b0g6mptvfd": {"type":"Pillows","score":49.9,"perf":19.9,"boost":30},
  "1688-1052742241013-c12": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-1052742241013-c11": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-1052742241013-c10": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-1052742241013-c9": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-1052742241013-c8": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-1052742241013-c7": {"type":"Mats","score":8,"perf":8,"boost":0},
  "1688-730512046265-c19": {"type":"Decor","score":10,"perf":10,"boost":0},
  "1688-730512046265-c18": {"type":"Decor","score":8,"perf":8,"boost":0},
  "1688-730512046265-c17": {"type":"Decor","score":10,"perf":10,"boost":0},
  "1688-730512046265-c16": {"type":"Decor","score":10,"perf":10,"boost":0},
  "1688-730512046265-c15": {"type":"Decor","score":10,"perf":10,"boost":0},
  "1688-730512046265-c14": {"type":"Decor","score":10,"perf":10,"boost":0},
};
