// Auto-generated by scripts/sync-materials.js
// DO NOT EDIT MANUALLY - Run 'node scripts/sync-materials.js' to update
// Generated at: 2026-09-19T11:53:14.833Z
// 素材库中站点上不存在的产品（无 Shopify 数据，统一显示 Out of Stock，建品后自动接上价格/库存）

import type { MakimooProduct } from './products';

export const MATERIALS_PRODUCTS: MakimooProduct[] = [
  {
    "id": "makimoo-1688-1052742241013-C12",
    "asin": "1688-1052742241013-C12",
    "title": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
    "handle": "vintage-persian-boho-area-rug-soft-faux-cashmere-non-slip-1688-1052742241013-c12",
    "description": "SOFT FAUX CASHMERE FEEL: This area rug features a faux cashmere surface that feels soft and cozy underfoot, adding warmth and comfort to your living room, bedroom, or seating area. VINTAGE PERSIAN BOHO STYLE: The rug showcases a Persian-inspired medallion pattern with boho details in orange and blue tones, bringing a vintage look that complements many home decor styles. NON SLIP SILICONE BACKING: A silicone backing helps reduce sliding on hard floors, so the rug stays in place during daily use and works well in busy spaces such as living rooms and bedside areas. VERSATILE HOME DECOR: With a 180 x 250cm size, this rug can be placed under a sofa, coffee table, or bed, or used as a decorative floor mat in the living room, bedroom, or other indoor areas. LOW PROFILE AND EASY MAINTENANCE: The 0.5cm low profile allows the rug to fit under furniture and doors; regular vacuuming and spot cleaning as needed help keep it looking neat and fresh.",
    "descriptionHtml": "<p>SOFT FAUX CASHMERE FEEL: This area rug features a faux cashmere surface that feels soft and cozy underfoot, adding warmth and comfort to your living room, bedroom, or seating area.</p><p>VINTAGE PERSIAN BOHO STYLE: The rug showcases a Persian-inspired medallion pattern with boho details in orange and blue tones, bringing a vintage look that complements many home decor styles.</p><p>NON SLIP SILICONE BACKING: A silicone backing helps reduce sliding on hard floors, so the rug stays in place during daily use and works well in busy spaces such as living rooms and bedside areas.</p><p>VERSATILE HOME DECOR: With a 180 x 250cm size, this rug can be placed under a sofa, coffee table, or bed, or used as a decorative floor mat in the living room, bedroom, or other indoor areas.</p><p>LOW PROFILE AND EASY MAINTENANCE: The 0.5cm low profile allows the rug to fit under furniture and doors; regular vacuuming and spot cleaning as needed help keep it looking neat and fresh.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C12/1.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C12/2.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C12/3.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C12/4.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C12/5.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C12/6.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Non Slip Silicone Backing For Living Room Bedroom Sofa Bedside Indoor Decorative Floor Carpet Mat 180 x 250 cm (Orange Blue)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "65.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C12",
        "title": "Default Title",
        "price": {
          "amount": "65.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-1052742241013-C11",
    "asin": "1688-1052742241013-C11",
    "title": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
    "handle": "vintage-boho-persian-area-rug-faux-cashmere-non-slip-1688-1052742241013-c11",
    "description": "VINTAGE BOHO DESIGN: This area rug features a classic Persian-inspired medallion pattern with rich orange, blue, and brown tones, bringing a warm retro bohemian feel to your living room, bedroom, or nursery. The intricate border and central motifs add artistic charm to your home decor. SOFT FAUX CASHMERE COMFORT: Crafted from faux cashmere material, this rug offers a plush, cozy surface that feels gentle underfoot. The soft texture makes it ideal for relaxing, playing, or walking barefoot, enhancing comfort in any indoor space. NON SLIP SILICONE BACKING: The silicone backing helps keep the rug securely in place on various floor types, reducing slips and shifts. This non slip design is suitable for high traffic areas and homes with children or pets, providing added stability. VERSATILE SIZE FOR MULTIPLE ROOMS: Measuring 140 x 200cm, this rectangular rug fits well in living rooms, bedrooms, beside the sofa, or at the bedside. Its generous size provides ample coverage while complementing different furniture arrangements and interior styles. EASY CARE AND LONG LASTING: The low pile construction resists dirt and is easy to maintain. Simply vacuum regularly and spot clean with a mild detergent when needed. The durable materials help the rug retain its shape and color over time.",
    "descriptionHtml": "<p>VINTAGE BOHO DESIGN: This area rug features a classic Persian-inspired medallion pattern with rich orange, blue, and brown tones, bringing a warm retro bohemian feel to your living room, bedroom, or nursery. The intricate border and central motifs add artistic charm to your home decor.</p><p>SOFT FAUX CASHMERE COMFORT: Crafted from faux cashmere material, this rug offers a plush, cozy surface that feels gentle underfoot. The soft texture makes it ideal for relaxing, playing, or walking barefoot, enhancing comfort in any indoor space.</p><p>NON SLIP SILICONE BACKING: The silicone backing helps keep the rug securely in place on various floor types, reducing slips and shifts. This non slip design is suitable for high traffic areas and homes with children or pets, providing added stability.</p><p>VERSATILE SIZE FOR MULTIPLE ROOMS: Measuring 140 x 200cm, this rectangular rug fits well in living rooms, bedrooms, beside the sofa, or at the bedside. Its generous size provides ample coverage while complementing different furniture arrangements and interior styles.</p><p>EASY CARE AND LONG LASTING: The low pile construction resists dirt and is easy to maintain. Simply vacuum regularly and spot clean with a mild detergent when needed. The durable materials help the rug retain its shape and color over time.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C11/1.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C11/2.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C11/3.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C11/4.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C11/5.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C11/6.webp",
        "altText": "Vintage Boho Persian Area Rug Faux Cashmere Non Slip Silicone Backing Soft Cozy Floor Carpet For Living Room Bedroom Sofa Bedside Nursery Decor 140 x 200 cm (Orange Blue)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "39.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C11",
        "title": "Default Title",
        "price": {
          "amount": "39.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-1052742241013-C10",
    "asin": "1688-1052742241013-C10",
    "title": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
    "handle": "vintage-bohemian-persian-boho-chic-area-rug-soft-faux-1688-1052742241013-c10",
    "description": "VINTAGE BOHO DESIGN: This area rug features a Persian inspired medallion with floral motifs and a gently distressed look, adding warm character to living rooms, bedrooms, dining spaces, and entryways. The teal blue, navy, beige, and blush palette pairs well with bohemian, farmhouse, and modern decor. SOFT FAUX CASHMERE COMFORT: The faux cashmere surface offers a cozy, soft feel underfoot, making this 140 x 200cm rug a comfortable choice for sofa areas, bedside placement, and relaxed floor seating. Its low 0.5cm profile fits easily under furniture and around doorways. NON SLIP SILICONE BACKING: A silicone backing helps keep the rug stable on hard floors and low pile carpets, reducing sliding and bunching during everyday use. This makes it a practical option for busy living rooms, hallways, and under coffee tables. VERSATILE ROOM ACCENT: Designed for flexible placement, this 140 x 200cm carpet works as a living room anchor, bedroom accent, sofa companion, or bedside mat. The vintage pattern complements both classic and contemporary home styles. EASY CARE AND LONG LASTING LOOK: Vacuum regularly and spot clean with a mild detergent to maintain the rug's soft texture and printed pattern. Finished edges and a durable faux cashmere surface help it handle daily foot traffic in family spaces.",
    "descriptionHtml": "<p>VINTAGE BOHO DESIGN: This area rug features a Persian inspired medallion with floral motifs and a gently distressed look, adding warm character to living rooms, bedrooms, dining spaces, and entryways. The teal blue, navy, beige, and blush palette pairs well with bohemian, farmhouse, and modern decor.</p><p>SOFT FAUX CASHMERE COMFORT: The faux cashmere surface offers a cozy, soft feel underfoot, making this 140 x 200cm rug a comfortable choice for sofa areas, bedside placement, and relaxed floor seating. Its low 0.5cm profile fits easily under furniture and around doorways.</p><p>NON SLIP SILICONE BACKING: A silicone backing helps keep the rug stable on hard floors and low pile carpets, reducing sliding and bunching during everyday use. This makes it a practical option for busy living rooms, hallways, and under coffee tables.</p><p>VERSATILE ROOM ACCENT: Designed for flexible placement, this 140 x 200cm carpet works as a living room anchor, bedroom accent, sofa companion, or bedside mat. The vintage pattern complements both classic and contemporary home styles.</p><p>EASY CARE AND LONG LASTING LOOK: Vacuum regularly and spot clean with a mild detergent to maintain the rug's soft texture and printed pattern. Finished edges and a durable faux cashmere surface help it handle daily foot traffic in family spaces.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C10/1.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C10/2.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C10/3.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C10/4.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C10/5.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C10/6.webp",
        "altText": "Vintage Bohemian Persian Boho Chic Area Rug Soft Faux Cashmere Non Slip Silicone Backing Carpet for Living Room Bedroom Sofa Bedside Home Decor 140 x 200 cm (Teal Blue)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "39.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C10",
        "title": "Default Title",
        "price": {
          "amount": "39.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-1052742241013-C9",
    "asin": "1688-1052742241013-C9",
    "title": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
    "handle": "vintage-persian-boho-area-rug-soft-faux-cashmere-anti-slip-1688-1052742241013-c9",
    "description": "VINTAGE PERSIAN BOHO DESIGN: This area rug features a classic Persian-inspired medallion pattern with floral motifs and a rich teal, navy, beige, and blush color palette. The vintage distressed look adds warmth and character to living rooms, bedrooms, and cozy seating areas. SOFT FAUX CASHMERE SURFACE: The plush faux cashmere top offers a gentle, velvety feel underfoot. It creates a comfortable spot for bare feet, pets, and children while bringing a soft textured layer to your home decor. ANTI SLIP SILICONE BACKING: Designed with a silicone backing, this rug helps stay securely in place on hard floors and low pile carpets. The anti slip construction reduces shifting and curling for safer everyday use in busy rooms. VERSATILE 180 x 250cm SIZE: Measuring 180 x 250cm, this rectangular rug fits well under coffee tables, at the foot of a bed, beside a sofa, or in a dining area. The low profile height of 0.5cm allows doors to open smoothly and works with many furniture layouts. EASY CARE & LOW MAINTENANCE: The non shedding surface is simple to maintain with regular vacuuming and spot cleaning. For long lasting beauty, rotate the rug occasionally and avoid prolonged direct sunlight.",
    "descriptionHtml": "<p>VINTAGE PERSIAN BOHO DESIGN: This area rug features a classic Persian-inspired medallion pattern with floral motifs and a rich teal, navy, beige, and blush color palette. The vintage distressed look adds warmth and character to living rooms, bedrooms, and cozy seating areas.</p><p>SOFT FAUX CASHMERE SURFACE: The plush faux cashmere top offers a gentle, velvety feel underfoot. It creates a comfortable spot for bare feet, pets, and children while bringing a soft textured layer to your home decor.</p><p>ANTI SLIP SILICONE BACKING: Designed with a silicone backing, this rug helps stay securely in place on hard floors and low pile carpets. The anti slip construction reduces shifting and curling for safer everyday use in busy rooms.</p><p>VERSATILE 180 x 250cm SIZE: Measuring 180 x 250cm, this rectangular rug fits well under coffee tables, at the foot of a bed, beside a sofa, or in a dining area. The low profile height of 0.5cm allows doors to open smoothly and works with many furniture layouts.</p><p>EASY CARE &amp; LOW MAINTENANCE: The non shedding surface is simple to maintain with regular vacuuming and spot cleaning. For long lasting beauty, rotate the rug occasionally and avoid prolonged direct sunlight.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C9/1.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C9/2.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C9/3.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C9/4.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C9/5.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C9/6.webp",
        "altText": "Vintage Persian Boho Area Rug Soft Faux Cashmere Anti Slip Silicone Backing Easy Care Non Shedding Distressed for Living Room Bedroom Bedside Home Decor 180 x 250 cm (Teal)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "65.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C9",
        "title": "Default Title",
        "price": {
          "amount": "65.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-1052742241013-C8",
    "asin": "1688-1052742241013-C8",
    "title": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
    "handle": "vintage-persian-area-rug-faux-cashmere-boho-non-slip-1688-1052742241013-c8",
    "description": "VINTAGE PERSIAN INSPIRED DESIGN: This area rug features a traditional medallion center, floral border, and soft sage green tones with beige and rust accents, bringing a warm bohemian look to living rooms, bedrooms, sofa areas, and bedside spaces. SOFT FAUX CASHMERE FEEL: The faux cashmere surface provides a gentle, cozy touch underfoot while keeping a low profile that fits everyday indoor areas. Its soft texture makes the rug a comfortable choice for relaxing, reading, or walking barefoot. NON SLIP SILICONE BACKING: The silicone backing helps hold the rug in place on hard floors and can reduce shifting when you walk, sit, or place light furniture on it. This design supports stable placement in busy living rooms, bedrooms, and bedside areas. VERSATILE 140 x 200cm SIZE: Measuring 140 x 200cm with a 0.5cm height, this area rug fits living room seating areas, under a coffee table, beside a bed, or in a bedroom as a soft decorative layer. The rectangular shape works with many furniture layouts. EASY DAILY CARE: Low pile construction allows simple upkeep for indoor spaces. Vacuum regularly on a low setting, spot clean gently with mild soap and a damp cloth, and roll or fold the rug for storage when needed.",
    "descriptionHtml": "<p>VINTAGE PERSIAN INSPIRED DESIGN: This area rug features a traditional medallion center, floral border, and soft sage green tones with beige and rust accents, bringing a warm bohemian look to living rooms, bedrooms, sofa areas, and bedside spaces.</p><p>SOFT FAUX CASHMERE FEEL: The faux cashmere surface provides a gentle, cozy touch underfoot while keeping a low profile that fits everyday indoor areas. Its soft texture makes the rug a comfortable choice for relaxing, reading, or walking barefoot.</p><p>NON SLIP SILICONE BACKING: The silicone backing helps hold the rug in place on hard floors and can reduce shifting when you walk, sit, or place light furniture on it. This design supports stable placement in busy living rooms, bedrooms, and bedside areas.</p><p>VERSATILE 140 x 200cm SIZE: Measuring 140 x 200cm with a 0.5cm height, this area rug fits living room seating areas, under a coffee table, beside a bed, or in a bedroom as a soft decorative layer. The rectangular shape works with many furniture layouts.</p><p>EASY DAILY CARE: Low pile construction allows simple upkeep for indoor spaces. Vacuum regularly on a low setting, spot clean gently with mild soap and a damp cloth, and roll or fold the rug for storage when needed.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C8/1.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C8/2.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C8/3.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C8/4.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C8/5.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C8/6.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Boho Non Slip Silicone Backing Oriental Medallion Soft Carpet for Living Room Bedroom Sofa Bedside Indoor 140 x 200 cm (Sage Green)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "39.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C8",
        "title": "Default Title",
        "price": {
          "amount": "39.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-1052742241013-C7",
    "asin": "1688-1052742241013-C7",
    "title": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
    "handle": "vintage-persian-area-rug-faux-cashmere-bohemian-non-slip-1688-1052742241013-c7",
    "description": "SOFT FAUX CASHMERE SURFACE: This area rug features a plush faux cashmere surface that feels gentle underfoot and adds a cozy layer to living rooms, bedrooms, and bedside areas. The soft texture helps create a warm, inviting spot for relaxing, reading, or spending time with family. NON SLIP SILICONE BACKING: The silicone backing is designed to help keep the rug stable on hard floors, reducing shifting during daily use. This feature makes it a practical choice for busy homes with kids or pets, and it works well under sofas, beds, and coffee tables. VINTAGE PERSIAN BOHEMIAN MOTIF: The rug showcases a traditional Persian-inspired medallion pattern with Bohemian details in a sage green palette and muted red accents. Its faded vintage look brings character to modern, farmhouse, or eclectic interiors without overpowering the room. VERSATILE 180 x 250cm SIZE: Measuring 180 x 250cm, this rug offers generous coverage for living room seating areas, bedroom floors, and bedside spaces. The low 0.5cm profile allows it to sit neatly under furniture and makes it easy to place in entryways or dining areas. EASY CARE AND LONG LASTING USE: Regular vacuuming and spot cleaning with a mild detergent help maintain the rug's appearance. The durable construction and non slip backing support everyday use in high traffic areas, making it a low maintenance addition to your home.",
    "descriptionHtml": "<p>SOFT FAUX CASHMERE SURFACE: This area rug features a plush faux cashmere surface that feels gentle underfoot and adds a cozy layer to living rooms, bedrooms, and bedside areas. The soft texture helps create a warm, inviting spot for relaxing, reading, or spending time with family.</p><p>NON SLIP SILICONE BACKING: The silicone backing is designed to help keep the rug stable on hard floors, reducing shifting during daily use. This feature makes it a practical choice for busy homes with kids or pets, and it works well under sofas, beds, and coffee tables.</p><p>VINTAGE PERSIAN BOHEMIAN MOTIF: The rug showcases a traditional Persian-inspired medallion pattern with Bohemian details in a sage green palette and muted red accents. Its faded vintage look brings character to modern, farmhouse, or eclectic interiors without overpowering the room.</p><p>VERSATILE 180 x 250cm SIZE: Measuring 180 x 250cm, this rug offers generous coverage for living room seating areas, bedroom floors, and bedside spaces. The low 0.5cm profile allows it to sit neatly under furniture and makes it easy to place in entryways or dining areas.</p><p>EASY CARE AND LONG LASTING USE: Regular vacuuming and spot cleaning with a mild detergent help maintain the rug's appearance. The durable construction and non slip backing support everyday use in high traffic areas, making it a low maintenance addition to your home.</p>",
    "productType": "Mats",
    "tags": [
      "Mats"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-1052742241013-C7/1.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C7/2.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C7/3.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C7/4.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C7/5.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-1052742241013-C7/6.webp",
        "altText": "Vintage Persian Area Rug Faux Cashmere Bohemian Non Slip Carpet for Living Room Bedroom Sofa Bedside Soft Plush Oriental Medallion Indoor Floor Mat 180 x 250 cm (Sage Green)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "65.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-1052742241013-C7",
        "title": "Default Title",
        "price": {
          "amount": "65.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C19",
    "asin": "1688-730512046265-C19",
    "title": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
    "handle": "african-style-woven-basket-motif-linen-wall-art-with-solid-1688-730512046265-c19",
    "description": "AFRICAN WOVEN BASKET MOTIF: This framed wall art features a detailed African-inspired woven basket design with geometric patterns and warm earth tones. The fabric background adds texture and depth, making it a striking focal point for global, bohemian, or African-inspired interiors. SOLID WOOD FRAME: The artwork is set in a solid wood frame with a natural brown finish that complements the earthy palette. Its 48 x 48 x 3cm square format gives the piece a balanced, gallery-style presence without overwhelming the wall. LINEN FABRIC SURFACE: This artwork is presented on a linen fabric surface with visible weave texture and a soft matte finish. The fabric ground gives the African basket motifs a warm, tactile look and pairs well with wood, rattan, and woven decor. VERSATILE HOSPITALITY AND HOME DECOR: Designed for hotels, restaurants, homestays, living rooms, and design studios, this square art piece adds cultural character to both residential and commercial spaces. It can be hung alone or grouped with other framed prints for a curated gallery wall. THOUGHTFUL GIFT FOR DESIGN LOVERS: An expressive accent for fans of African-inspired decor, interior designers, and anyone updating a guest room, dining area, or lounge. The framed format makes it a considerate choice for housewarmings and space refreshes.",
    "descriptionHtml": "<p>AFRICAN WOVEN BASKET MOTIF: This framed wall art features a detailed African-inspired woven basket design with geometric patterns and warm earth tones. The fabric background adds texture and depth, making it a striking focal point for global, bohemian, or African-inspired interiors.</p><p>SOLID WOOD FRAME: The artwork is set in a solid wood frame with a natural brown finish that complements the earthy palette. Its 48 x 48 x 3cm square format gives the piece a balanced, gallery-style presence without overwhelming the wall.</p><p>LINEN FABRIC SURFACE: This artwork is presented on a linen fabric surface with visible weave texture and a soft matte finish. The fabric ground gives the African basket motifs a warm, tactile look and pairs well with wood, rattan, and woven decor.</p><p>VERSATILE HOSPITALITY AND HOME DECOR: Designed for hotels, restaurants, homestays, living rooms, and design studios, this square art piece adds cultural character to both residential and commercial spaces. It can be hung alone or grouped with other framed prints for a curated gallery wall.</p><p>THOUGHTFUL GIFT FOR DESIGN LOVERS: An expressive accent for fans of African-inspired decor, interior designers, and anyone updating a guest room, dining area, or lounge. The framed format makes it a considerate choice for housewarmings and space refreshes.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C19/1.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C19/2.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C19/3.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C19/4.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C19/5.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C19/6.webp",
        "altText": "African Style Woven Basket Motif Linen Wall Art With Solid Wood Frame Decorative Painting For Hotel Restaurant Homestay Designer Soft Furnishings 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C19",
        "title": "Default Title",
        "price": {
          "amount": "89.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C18",
    "asin": "1688-730512046265-C18",
    "title": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
    "handle": "square-african-style-woven-fabric-wall-art-with-solid-wood-1688-730512046265-c18",
    "description": "AFRICAN INSPIRED WOVEN DESIGN: This square wall art features a woven fabric surface decorated with motifs inspired by traditional African baskets and vessels, bringing a rich cultural and artistic touch to your interior. SOLID WOOD FRAME: The artwork is encased in a solid wood frame that adds natural warmth and durability, while the woven fabric panel creates a tactile texture that stands out on any wall. VERSATILE DECOR FIT: Designed for hotel, restaurant, cafe, bedroom, living room, office, and guesthouse settings, this piece complements rustic, ethnic, bohemian, and modern farmhouse styles. SQUARE 48 x 48 x 3cm SIZE: With a compact 48 x 48 x 3cm square profile, this framed fabric art fits easily into various wall spaces, from small accent walls to larger gallery arrangements. THOUGHTFUL GIFT IDEA: This African style woven wall art makes a considerate gift for housewarmings, birthdays, and special occasions, appealing to lovers of cultural decor and artisan-inspired interiors.",
    "descriptionHtml": "<p>AFRICAN INSPIRED WOVEN DESIGN: This square wall art features a woven fabric surface decorated with motifs inspired by traditional African baskets and vessels, bringing a rich cultural and artistic touch to your interior.</p><p>SOLID WOOD FRAME: The artwork is encased in a solid wood frame that adds natural warmth and durability, while the woven fabric panel creates a tactile texture that stands out on any wall.</p><p>VERSATILE DECOR FIT: Designed for hotel, restaurant, cafe, bedroom, living room, office, and guesthouse settings, this piece complements rustic, ethnic, bohemian, and modern farmhouse styles.</p><p>SQUARE 48 x 48 x 3cm SIZE: With a compact 48 x 48 x 3cm square profile, this framed fabric art fits easily into various wall spaces, from small accent walls to larger gallery arrangements.</p><p>THOUGHTFUL GIFT IDEA: This African style woven wall art makes a considerate gift for housewarmings, birthdays, and special occasions, appealing to lovers of cultural decor and artisan-inspired interiors.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C18/1.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C18/2.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C18/3.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C18/4.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C18/5.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C18/6.webp",
        "altText": "Square African Style Woven Fabric Wall Art with Solid Wood Frame Rustic Ethnic Boho Home Decor for Hotel Restaurant Cafe Bedroom Living Room Office 48 x 48 x 3 cm (Multicolor)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C18",
        "title": "Default Title",
        "price": {
          "amount": "89.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C17",
    "asin": "1688-730512046265-C17",
    "title": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
    "handle": "ethnic-linen-framed-wall-art-greek-figure-motif-vintage-1688-730512046265-c17",
    "description": "GREEK FIGURE MOTIF: This framed wall art features a classic Greek figure design inspired by ancient pottery, bringing a distinctive artistic and cultural touch to your interior decor. LINEN FABRIC SURFACE: Printed on linen fabric, the artwork offers a textured look and rich color presentation that complements ethnic, vintage, and artistic room styles. STURDY WOODEN FRAME: The wooden frame surrounds the print, providing structure and a natural warm tone that suits hotel, restaurant, homestay, and home settings. VERSATILE PLACEMENT: Measuring 38 x 48cm, this decorative piece works well in living rooms, bedrooms, offices, hallways, and commercial spaces such as cafes and guesthouses. READY FOR DISPLAY: The framed design allows for simple wall mounting, making it easy to add a cultural accent to your space without complex installation.",
    "descriptionHtml": "<p>GREEK FIGURE MOTIF: This framed wall art features a classic Greek figure design inspired by ancient pottery, bringing a distinctive artistic and cultural touch to your interior decor.</p><p>LINEN FABRIC SURFACE: Printed on linen fabric, the artwork offers a textured look and rich color presentation that complements ethnic, vintage, and artistic room styles.</p><p>STURDY WOODEN FRAME: The wooden frame surrounds the print, providing structure and a natural warm tone that suits hotel, restaurant, homestay, and home settings.</p><p>VERSATILE PLACEMENT: Measuring 38 x 48cm, this decorative piece works well in living rooms, bedrooms, offices, hallways, and commercial spaces such as cafes and guesthouses.</p><p>READY FOR DISPLAY: The framed design allows for simple wall mounting, making it easy to add a cultural accent to your space without complex installation.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C17/1.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C17/2.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C17/3.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C17/4.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C17/5.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C17/6.webp",
        "altText": "Ethnic Linen Framed Wall Art Greek Figure Motif Vintage Fabric Print Decorative Accent for Hotel Restaurant Homestay Bedroom Living Room Office 38 x 48 cm (Brown)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "59.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C17",
        "title": "Default Title",
        "price": {
          "amount": "59.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C16",
    "asin": "1688-730512046265-C16",
    "title": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
    "handle": "ethnic-burlap-wall-art-decorative-painting-for-hotel-1688-730512046265-c16",
    "description": "ETHNIC AFRICAN VIKING INSPIRED DESIGN: This square wall art features a striking circular medallion with geometric tribal patterns and a textured burlap surface, bringing a bold global accent to any room. The intricate motif combines African and Viking style elements for a distinctive designer look. SOLID WOOD FRAME AND BURLAP CANVAS: The artwork is set in a sturdy solid wood frame that adds warmth and durability. The burlap canvas texture enhances the artisanal feel and complements the earthy brown tones. VERSATILE FOR HOTEL RESTAURANT AND GUESTHOUSE: Ideal for hospitality settings, this decorative painting elevates hotel lobbies, restaurant walls, and guesthouse interiors. It also works well in living rooms, bedrooms, and entryways for a cohesive ethnic aesthetic. READY TO DISPLAY SQUARE FORMAT: Measuring 48 x 48 x 3cm, this compact square piece fits various wall spaces. The framed construction allows for easy hanging and immediate display as a focal point. DESIGNER FABRIC SOFT FURNISHING ACCENT: This fabric wall art serves as a designer soft furnishing accent that pairs with modern, bohemian, or rustic decor. Its neutral brown palette and textured surface add depth and character to any interior.",
    "descriptionHtml": "<p>ETHNIC AFRICAN VIKING INSPIRED DESIGN: This square wall art features a striking circular medallion with geometric tribal patterns and a textured burlap surface, bringing a bold global accent to any room. The intricate motif combines African and Viking style elements for a distinctive designer look.</p><p>SOLID WOOD FRAME AND BURLAP CANVAS: The artwork is set in a sturdy solid wood frame that adds warmth and durability. The burlap canvas texture enhances the artisanal feel and complements the earthy brown tones.</p><p>VERSATILE FOR HOTEL RESTAURANT AND GUESTHOUSE: Ideal for hospitality settings, this decorative painting elevates hotel lobbies, restaurant walls, and guesthouse interiors. It also works well in living rooms, bedrooms, and entryways for a cohesive ethnic aesthetic.</p><p>READY TO DISPLAY SQUARE FORMAT: Measuring 48 x 48 x 3cm, this compact square piece fits various wall spaces. The framed construction allows for easy hanging and immediate display as a focal point.</p><p>DESIGNER FABRIC SOFT FURNISHING ACCENT: This fabric wall art serves as a designer soft furnishing accent that pairs with modern, bohemian, or rustic decor. Its neutral brown palette and textured surface add depth and character to any interior.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C16/1.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C16/2.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C16/3.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C16/4.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C16/5.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C16/6.webp",
        "altText": "Ethnic Burlap Wall Art Decorative Painting For Hotel Restaurant Guesthouse African Viking Style Designer Fabric Soft Furnishing Solid Wood Frame Square 48 x 48 x 3 cm (Brown)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C16",
        "title": "Default Title",
        "price": {
          "amount": "89.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C15",
    "asin": "1688-730512046265-C15",
    "title": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
    "handle": "african-ethnic-decorative-burlap-framed-wall-art-featuring-1688-730512046265-c15",
    "description": "AFRICAN ETHNIC MOTIF: This framed wall art features a collection of circular woven basket patterns set against a linen-like burlap background, bringing a warm tribal and bohemian touch to any room. The earthy tones of brown, beige, and black create a grounded, natural look. TEXTURED BURLAP CANVAS: The artwork is printed on a textured fabric surface that resembles burlap, giving it a rustic, handcrafted feel. The dark wood frame adds depth and complements the organic design, making it a standout decorative piece. VERSATILE ROOM ACCENT: With a compact size of 48 x 38cm, this framed print fits easily above a console table, in a gallery wall, or as a focal point in smaller spaces. It suits living rooms, bedrooms, offices, and hotel or homestay interiors. DESIGNER SOFT DECOR: Ideal for interior designers and style-conscious homeowners, this piece blends African-inspired art with modern rustic decor. It works well in bohemian, eclectic, farmhouse, or global-inspired settings, adding cultural character without overwhelming the space. READY TO DISPLAY: This framed artwork is ready for wall placement, making a thoughtful gift for housewarmings, art lovers, or anyone who appreciates ethnic-inspired home accents. The 3cm frame profile provides a substantial, finished look.",
    "descriptionHtml": "<p>AFRICAN ETHNIC MOTIF: This framed wall art features a collection of circular woven basket patterns set against a linen-like burlap background, bringing a warm tribal and bohemian touch to any room. The earthy tones of brown, beige, and black create a grounded, natural look.</p><p>TEXTURED BURLAP CANVAS: The artwork is printed on a textured fabric surface that resembles burlap, giving it a rustic, handcrafted feel. The dark wood frame adds depth and complements the organic design, making it a standout decorative piece.</p><p>VERSATILE ROOM ACCENT: With a compact size of 48 x 38cm, this framed print fits easily above a console table, in a gallery wall, or as a focal point in smaller spaces. It suits living rooms, bedrooms, offices, and hotel or homestay interiors.</p><p>DESIGNER SOFT DECOR: Ideal for interior designers and style-conscious homeowners, this piece blends African-inspired art with modern rustic decor. It works well in bohemian, eclectic, farmhouse, or global-inspired settings, adding cultural character without overwhelming the space.</p><p>READY TO DISPLAY: This framed artwork is ready for wall placement, making a thoughtful gift for housewarmings, art lovers, or anyone who appreciates ethnic-inspired home accents. The 3cm frame profile provides a substantial, finished look.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C15/1.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C15/2.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C15/3.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C15/4.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C15/5.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C15/6.webp",
        "altText": "African Ethnic Decorative Burlap Framed Wall Art Featuring Circular Basket Weave Motifs Rustic Tribal Decor For Living Room Bedroom Hotel Office Studio 48 x 38 cm (Brown)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "59.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C15",
        "title": "Default Title",
        "price": {
          "amount": "59.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  },
  {
    "id": "makimoo-1688-730512046265-C14",
    "asin": "1688-730512046265-C14",
    "title": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
    "handle": "ancient-greek-mythology-pottery-style-linen-wall-art-with-1688-730512046265-c14",
    "description": "ANCIENT GREEK POTTERY ART STYLE: This linen wall art features classic Greek pottery inspired figures, including warriors and robed characters, rendered in a striking black and terracotta palette. The design brings a classic museum style charm to hotel lobbies, restaurants, cafes, and homestays. QUALITY LINEN AND SOLID WOOD FRAME: The decorative fabric painting is mounted in a sturdy solid wood frame that adds warmth and structure. Measuring 48 x 48cm with a 3cm depth, it offers a substantial presence on the wall without overwhelming the room. VERSATILE FOR COMMERCIAL AND HOME DECOR: Ideal for hospitality settings such as hotels, restaurants, and guesthouses, this piece also works well in living rooms, bedrooms, offices, and creative studio spaces. Its designer textile look complements eclectic, vintage, and global inspired interiors. DISTINCTIVE VISUAL CENTERPIECE: The framed artwork uses bold silhouette motifs and geometric border patterns to create a captivating focal point. The neutral linen ground and warm accent panels make it easy to pair with wood furniture, plants, and earthy color schemes. THOUGHTFUL GIFT FOR ART AND DECOR LOVERS: This Greek style fabric wall art makes a considerate present for art lovers, friends, and family who appreciate classical art and cultural decor. It comes framed and can enhance a gallery wall or standalone display.",
    "descriptionHtml": "<p>ANCIENT GREEK POTTERY ART STYLE: This linen wall art features classic Greek pottery inspired figures, including warriors and robed characters, rendered in a striking black and terracotta palette. The design brings a classic museum style charm to hotel lobbies, restaurants, cafes, and homestays.</p><p>QUALITY LINEN AND SOLID WOOD FRAME: The decorative fabric painting is mounted in a sturdy solid wood frame that adds warmth and structure. Measuring 48 x 48cm with a 3cm depth, it offers a substantial presence on the wall without overwhelming the room.</p><p>VERSATILE FOR COMMERCIAL AND HOME DECOR: Ideal for hospitality settings such as hotels, restaurants, and guesthouses, this piece also works well in living rooms, bedrooms, offices, and creative studio spaces. Its designer textile look complements eclectic, vintage, and global inspired interiors.</p><p>DISTINCTIVE VISUAL CENTERPIECE: The framed artwork uses bold silhouette motifs and geometric border patterns to create a captivating focal point. The neutral linen ground and warm accent panels make it easy to pair with wood furniture, plants, and earthy color schemes.</p><p>THOUGHTFUL GIFT FOR ART AND DECOR LOVERS: This Greek style fabric wall art makes a considerate present for art lovers, friends, and family who appreciate classical art and cultural decor. It comes framed and can enhance a gallery wall or standalone display.</p>",
    "productType": "Decor",
    "tags": [
      "Decor"
    ],
    "availableForSale": true,
    "images": [
      {
        "url": "/images/products/1688-730512046265-C14/1.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C14/2.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C14/3.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C14/4.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C14/5.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      },
      {
        "url": "/images/products/1688-730512046265-C14/6.webp",
        "altText": "Ancient Greek Mythology Pottery Style Linen Wall Art with Solid Wood Frame Decorative Fabric Painting for Hotel Cafe Restaurant Home Office Decor 48 x 48 cm (Multicolor)",
        "width": 800,
        "height": 800
      }
    ],
    "priceRange": {
      "minVariantPrice": {
        "amount": "89.99",
        "currencyCode": "USD"
      }
    },
    "variants": [
      {
        "id": "variant-1688-730512046265-C14",
        "title": "Default Title",
        "price": {
          "amount": "89.99",
          "currencyCode": "USD"
        },
        "availableForSale": true,
        "selectedOptions": []
      }
    ],
    "amazonUrl": ""
  }
];
